import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import router from "./router";
import "ol/ol.css";
import "./style.css";

const app = createApp(App);
app.use(createPinia());
app.use(router);
app.mount("#app");

// PWA: register the service worker generated by vite-plugin-pwa.
// `autoUpdate` mode silently installs new builds; the next page reload
// activates them. Skipped over file:// (Electron) where SW isn't supported.
if ("serviceWorker" in navigator && location.protocol.startsWith("http")) {
  import("virtual:pwa-register")
    .then(({ registerSW }) => {
      registerSW({
        immediate: true,
        onRegisteredSW(_, r) {
          // While the tab stays open, poll for new builds every hour
          if (r) setInterval(() => r.update().catch(() => {}), 60 * 60 * 1000);
        },
        onOfflineReady() {
          console.log("[PWA] Ready to work offline");
        },
        onRegisterError(err) {
          console.warn("[PWA] Service worker registration failed:", err);
        },
      });
    })
    .catch(() => {
      /* Virtual module not present (e.g. dev mode without PWA enabled) */
    });
}
